Project 1/wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("new_page", views.new, name = "new"),
    path("random", views.random, name = "random"),
    path("wiki/<str:title>/edit",views.edit, name="edit"),   
    
]

Project 1/wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

Project 1/wiki/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

Project 1/wiki/wiki/encyclopedia/views.py
from doctest import FAIL_FAST
from email.encoders import encode_7or8bit
from random import randint
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse

import markdown
from . import util
class SearchForm(forms.Form):
    q = forms.CharField(label='',
     widget= forms.TextInput(attrs={'placeholder':'Search Encyclopedia',
    'class':'q','autocomplete':'off'}))
class CreateNewPage(forms.Form):
    title = forms.CharField(label='',
        widget= forms.TextInput(attrs={'placeholder':'Enter title','class ':'title','autocomplete':'off','autofocus':True}))
    content = forms.CharField(label='',
        widget= forms.Textarea(attrs={'placeholder':'Enter the content',
         'class ':'content','autocomplete':'off'}))
class EditPage(forms.Form):
    # Making the title field uneditable 
    title = forms.CharField(label='',required=False,disabled=True,
        widget= forms.TextInput(attrs={'placeholder':'','class':'title'}))
    content = forms.CharField(label='',
        widget= forms.Textarea(attrs={'placeholder':'',
        'style':'width:1000px; height:400px; overflow-y: off','autocomplete':'off'}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
        ,"form": SearchForm()
    })
def entry(request, title):
    # Checking if the desired title is in the encyclopedia
    if util.get_entry(title) == None:
        return render(request, "encyclopedia/error.html", {
            "title": title,
            "form": SearchForm()
            ,"exist": False
         
        })
    else:
        # Taking the information formated as Markdown code
        mdInfo = util.get_entry(title)
        # Convertion Markdown text into an html text
        info = markdown.markdown(mdInfo)
        # Showing the search result
   
        return render(request, "encyclopedia/entry.html", {
            "info": info,
            "form": SearchForm()
           , "title":title
        })
def search(request):
    if request.method == "GET":
        # The submited value
        form = request.GET['q']
        # A list of all entries
        all_entries = util.list_entries()
        found_entries = []
        
            # search for all the listed entries
        for entry in all_entries:
                if form.lower() == entry.lower():
                    return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={'title':form}))
                # appending the list the entries
                elif form.lower() in entry.lower():
                    found_entries.append(entry)
        if not found_entries:
            # If search not found showing an error page
            return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={'title':form}))
    # Rendring result page with a list of all antries that has
    # the querey as substring       
    return render(request,"encyclopedia/search.html",{
        "result": form,
        "entries": found_entries,
        "form": SearchForm()
    })

def new(request):
    if request.method == "POST":

        title = request.POST["title"]
        content = request.POST["content"]
        exist = False
        all_entries = util.list_entries()
        for entry in all_entries:
            # Checking if the new page is already in our entries
            if title.lower() == entry.lower():
                exist = True
                # if the page is found there will an error message that will be
                # shown to the user
                return render(request, "encyclopedia/new_page.html", {
                            "new": CreateNewPage(),
                            "form": SearchForm()
                            ,"exist": exist,
                            "title": title
                        })
        # If the new entry didn't exist 
        # then save it and redirect the user to the new page he created
        if not exist:
            util.save_entry(title,content)
            return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={'title':title}))

                
    return render(request,"encyclopedia/new_page.html",{
        "form": SearchForm(),
        "new": CreateNewPage()
        ,"exist": False
    })
def random(request):
    if request.method=="GET":
        all_entries = util.list_entries()
        # Creating a radnom index for the user to shown a random entry 
        index = randint(0,len(all_entries)-1)
        entry = all_entries[index]
        return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={'title':entry}))
def edit(request,title):
   if request.method =="GET":
       # At first we render the editing form with the pre existing informataton in the textarea
        info = util.get_entry(title)
        form = EditPage(initial={"title":title,"content":info})

        return render(request,"encyclopedia/edit.html",{
            "form":SearchForm(),
            "new":form,
            "info":info
            ,"title":title
        })
    # When the user submit the form update the information and redirect the user 
    # To the updated page
   if request.method == "POST":
        updatedInfo = request.POST['content']
        util.save_entry(title,updatedInfo)
        return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={'title':title}))    

Project 1/wiki/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit page
    
{% endblock %}
{% block body %}

  
    <form action ="{% url 'encyclopedia:edit' title%}" method ="POST">
        {{ new }}
        {%csrf_token%}
        <br>
        <button>Update</button>
    </form>

{% endblock %}

Project 1/wiki/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  {{ title }}
{% endblock %}  
{% block body%}


    <!--To change it from an html text to regular text--> 
        {{ info| safe }}
  <form action = "{% url 'encyclopedia:edit' title %}" method ="GET">
    {% csrf_token %}
    <button>Edit</button>
  </form>

        
{% endblock %}

Project 1/wiki/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  {{ title }}
{% endblock %}  
{% block body%}
  {% if exist %}
    <h1>{{ title }} already existed</h1>
  {% else %}
    <h1>{{ title }} not found </h1>
  {% endif %}
  
    
{% endblock %}

Project 1/wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li> <a href = "{% url 'encyclopedia:entry' entry %}" >{{ entry }}</a><br></li>
        {% endfor %}
    </ul> 

{% endblock %}

Project 1/wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form  action = "{% url 'encyclopedia:search' %}" mehtod = "GET">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                   <a href="{% url 'encyclopedia:new' %}">Create New Page</a> 
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}"> Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Project 1/wiki/wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create new page
    
{% endblock %}
{% block body %}
<form id="form1" action = "{% url 'encyclopedia:new' %}" method="POST">
    {% csrf_token %}
    {{ new }}
</form>
<button type="submit" form="form1" value ="submit">Save</button>
        {% if exist %}
        <div class="alert alert-danger" role="alert">
          {{ title }} already exist please resubmit the form.
        </div>
        {% endif %}
{% endblock %}

Project 1/wiki/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}
{% block body %}
<h1>Showing the result for {{ result }}</h1>

<ul>
    {% for entry in entries %}
        <li><a href = "{% url 'encyclopedia:entry' entry %}" >{{ entry }}</a><br></li>
    {% endfor %}
</ul>
{% endblock %}

Project 1/wiki/wiki/encyclopedia/templates/encyclopedia/update.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  {{ title }}
{% endblock %}  
{% block body%}


    <!--To change it from an html text to regular text--> 

  <form action = "{% url 'encyclopedia:edit' title %}" method ="GET">
    {% csrf_token %}
    <button>Edit</button>
  </form>

        
{% endblock %}